name: Run Unittests
on:
  push:
    branches: [master]
  pull_request:

jobs:
  dubtest:
    name: Dub Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        timeout-minutes: 5
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test
        timeout-minutes: 5
